/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    sessions: Session;
    activities: Activity;
    exercises: Exercise;
    progressions: Progression;
    workouts: Workout;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    sessions: SessionsSelect<false> | SessionsSelect<true>;
    activities: ActivitiesSelect<false> | ActivitiesSelect<true>;
    exercises: ExercisesSelect<false> | ExercisesSelect<true>;
    progressions: ProgressionsSelect<false> | ProgressionsSelect<true>;
    workouts: WorkoutsSelect<false> | WorkoutsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    weekplan: Weekplan;
  };
  globalsSelect: {
    weekplan: WeekplanSelect<false> | WeekplanSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sessions".
 */
export interface Session {
  id: number;
  user: number | User;
  /**
   * „datum-workout“ – macht Import und Sync wiederholbar
   */
  key: string;
  date: string;
  workout: string | Workout;
  durationSec?: number | null;
  sets?:
    | {
        exercise: string | Exercise;
        progression?: (string | null) | Progression;
        set: number;
        value: number;
        weightKg?: number | null;
        attempts?: number | null;
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  skipped?: (string | Exercise)[] | null;
  routineDone?: string[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  state?: {
    /**
     * Progressions-ID → Übungs-ID (nicht Stufen-Index)
     */
    current?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    paused?: (string | Progression)[] | null;
  };
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "progressions".
 */
export interface Progression {
  /**
   * Stabile ID (Slug, z. B. „chest-to-bar-pull-up“). Einmal vergeben, nie ändern.
   */
  id: string;
  /**
   * Reihenfolge = Progression. Die Vorgabe gehört zur Stufe, nicht zur Übung.
   */
  steps?:
    | {
        exercise: string | Exercise;
        target: {
          label: string;
          sets: number;
          min?: number | null;
          max?: number | null;
          restSec: number;
          unlockAt?: number | null;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exercises".
 */
export interface Exercise {
  /**
   * Stabile ID (Slug, z. B. „chest-to-bar-pull-up“). Einmal vergeben, nie ändern.
   */
  id: string;
  name: string;
  unit: 'reps' | 'seconds';
  weighted?: boolean | null;
  perSide?: boolean | null;
  technique?: {
    setup?: string | null;
    execution?: string | null;
    faults?: string | null;
    scaling?: string | null;
  };
  media?: {
    sketch?: string | null;
    videoQuery?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "workouts".
 */
export interface Workout {
  /**
   * Stabile ID (Slug, z. B. „chest-to-bar-pull-up“). Einmal vergeben, nie ändern.
   */
  id: string;
  name: string;
  focus?: string | null;
  /**
   * Reihenfolge = Trainingsreihenfolge
   */
  slots?:
    | {
        block: 'skill' | 'strength' | 'core' | 'accessory' | 'extra';
        progression: string | Progression;
        id?: string | null;
      }[]
    | null;
  warmup?:
    | {
        key: string;
        name: string;
        detail?: string | null;
        cardio?: boolean | null;
        id?: string | null;
      }[]
    | null;
  cooldown?:
    | {
        key: string;
        name: string;
        detail?: string | null;
        cardio?: boolean | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activities".
 */
export interface Activity {
  id: number;
  user: number | User;
  key: string;
  date: string;
  kind: 'run' | 'ride' | 'workout';
  name?: string | null;
  durationMin?: number | null;
  distanceKm?: number | null;
  elevationM?: number | null;
  rounds?: number | null;
  note?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'sessions';
        value: number | Session;
      } | null)
    | ({
        relationTo: 'activities';
        value: number | Activity;
      } | null)
    | ({
        relationTo: 'exercises';
        value: string | Exercise;
      } | null)
    | ({
        relationTo: 'progressions';
        value: string | Progression;
      } | null)
    | ({
        relationTo: 'workouts';
        value: string | Workout;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sessions_select".
 */
export interface SessionsSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  date?: T;
  workout?: T;
  durationSec?: T;
  sets?:
    | T
    | {
        exercise?: T;
        progression?: T;
        set?: T;
        value?: T;
        weightKg?: T;
        attempts?: T;
        note?: T;
        id?: T;
      };
  skipped?: T;
  routineDone?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activities_select".
 */
export interface ActivitiesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  date?: T;
  kind?: T;
  name?: T;
  durationMin?: T;
  distanceKm?: T;
  elevationM?: T;
  rounds?: T;
  note?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exercises_select".
 */
export interface ExercisesSelect<T extends boolean = true> {
  id?: T;
  name?: T;
  unit?: T;
  weighted?: T;
  perSide?: T;
  technique?:
    | T
    | {
        setup?: T;
        execution?: T;
        faults?: T;
        scaling?: T;
      };
  media?:
    | T
    | {
        sketch?: T;
        videoQuery?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "progressions_select".
 */
export interface ProgressionsSelect<T extends boolean = true> {
  id?: T;
  steps?:
    | T
    | {
        exercise?: T;
        target?:
          | T
          | {
              label?: T;
              sets?: T;
              min?: T;
              max?: T;
              restSec?: T;
              unlockAt?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "workouts_select".
 */
export interface WorkoutsSelect<T extends boolean = true> {
  id?: T;
  name?: T;
  focus?: T;
  slots?:
    | T
    | {
        block?: T;
        progression?: T;
        id?: T;
      };
  warmup?:
    | T
    | {
        key?: T;
        name?: T;
        detail?: T;
        cardio?: T;
        id?: T;
      };
  cooldown?:
    | T
    | {
        key?: T;
        name?: T;
        detail?: T;
        cardio?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  state?:
    | T
    | {
        current?: T;
        paused?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "weekplan".
 */
export interface Weekplan {
  id: number;
  mon?: (string | null) | Workout;
  tue?: (string | null) | Workout;
  wed?: (string | null) | Workout;
  thu?: (string | null) | Workout;
  fri?: (string | null) | Workout;
  sat?: (string | null) | Workout;
  sun?: (string | null) | Workout;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "weekplan_select".
 */
export interface WeekplanSelect<T extends boolean = true> {
  mon?: T;
  tue?: T;
  wed?: T;
  thu?: T;
  fri?: T;
  sat?: T;
  sun?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}